### PR TITLE
Adds possibility to override API parameters

### PR DESCRIPTION
**Pull request by timofey-l**
You made great extension!
Thank you for that :smile: 
We use it in our projects and it works well.
But sometimes we need to set some parameters (`track_opens` and `track_clicks` for now) to different value than default.
It can be possible in the future that Mandrill API will be changed and additional parameters could appear.
I think it would be useful to have the possibility to change any param before sending the request.
In one project I did it by creating a custom message class which extends your `Message` class.

Thanks for attention.

### CODE REVIEW

**Comment by nickcv-ln** [comment]
Hi @timofey-l thanks for the contribution!

I will definitely merge this in. Could you please add the corresponding tests for the getter and setter?
Don't worry about the actual sending tests.

**Comment by timofey-l** [comment]
@nickcv-ln Done!

**Comment by nickcv-ln** [comment]
@timofey-l thx! could you please resolve the conflicts? I cannot merge otherwise.

**Comment by timofey-l** [comment]
@nickcv-ln Sure! I will do it as soon as possible)

**Comment by timofey-l** [comment]
@nickcv-ln Done! All conflicts were resolved.
Just noticed that you already added support for `track` options =)

**Comment by simialbi** [comment]
Hey @timofey-l 
Good point, but in my opinion, something like
```php
    /**
     * Returns the array used by the Mandrill Class to initialize a message
     * and submit it.
     *
     * @param array $overrides Allows to override params before sending request to Mandrill API
     * @return array
     */
    public function getMandrillMessageArray($overrides = [])
    {
        return ArrayHelper::merge([
            'headers' => [
                'Reply-To' => $this->getReplyToString(),
            ],
            'html' => $this->getHtmlBody(),
            'text' => $this->getTextBody(),
            'subject' => $this->getSubject(),
            'from_email' => $this->getFromAddress(),
            'from_name' => $this->getFromName(),
            'to' => $this->getAllRecipients(),
            'track_opens' => $this->_trackOpens,
            'track_clicks' => $this->_trackClicks,
            'tags' => $this->_tags,
            'merge_language' => $this->_mergeLanguage,
            'global_merge_vars' => $this->_globalMergeVars,
            'merge_vars' => $this->_mergeVars,
            'metadata' => $this->_metadata,
            'recipient_metadata' => $this->_recipientMetadata,
            'google_analytics_domains' => $this->_googleAnalyticsDomains,
            'google_analytics_campaign' => $this->_googleAnalyticsCampaign,
            'attachments' => $this->_attachments,
            'images' => $this->_images,
            'subaccount' => $this->_subaccount,
            'important' => $this->_important
        ], $overrides);
    }
```
makes more sense. I think you only need these overrides at this special point so there is no need to have a class variable including getter and setter for this. @timofey-l and @nickcv-ln what do you think?

**Pull request closed without merging**
