### PR TITLE
add option to show detailed response from mandrill API

### PR DESCRIPTION
**Pull request by Nuffic**

### CODE REVIEW

**Comment by nickcv-ln** [comment]
Hi @Nuffic 
The PR is really straightforward, but I don't think I can do that change without breaking the contract established by the BaseMailer.

The `BaseMailer::sendMessage` method is supposed to return a boolean: returning the array generated by mandrill would break this requirement.

**Comment by Nuffic** [comment]
Hi! 

What about storing `$mandrillResponse` in a private property? So that it can be accessed via getter after `BaseMailer::sendMessage()` has been run.

**Comment by nickcv-ln** [comment]
That's a good solution.
I can change the default behavior so that the last transaction is always stored in the mailer.

i.e.:

``` php
\Yii::$app->mailer->getLastTransaction()
```

**Comment by nickcv-ln** [comment]
@Nuffic  If you are not willing to take over the work I will close this PR and create an issue btw!

**Comment by Nuffic** [comment]
Hi! 

Added  getter as discussed before. Also added option to set Mandrill subaccount.

**Pull request merged**
